name: Test Email Step

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f1002492@ds.study.iitm.ac.in
        run: echo "Hello, world!"
